[package]
name = "statsd"
version = "0.1.2"
description = "A basic statsd client for rust."
homepage = "https://github.com/markstory/statsd-rust"
readme = "README.md"
license = "MIT"
authors = ["Mark Story <mark@mark-story.com>"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE.md",
]

[dependencies]
clock_ticks = "0.0.6"
rand = "0.3"
